from __future__ import annotations
from typing import Union, Sequence, Optional, Tuple
import numpy as np
import jax
import jax.numpy as jnp
from functools import partial
import quantax as qtx
from quantax.global_defs import PARTICLE_TYPE, get_sites, get_lattice, get_default_dtype


_Identity = None
_Z2Inverse = dict()


@jax.jit
@partial(jax.vmap, in_axes=(None, 0, 0))
def _permutation_sign(
    spins: jax.Array, perm: jax.Array, perm_sign: jax.Array
) -> jax.Array:
    """Compute the permutation sign. This function will be slow if Nparticles is None"""
    perm = jnp.argsort(perm)  # invert permmutation

    Ntotal = get_sites().Ntotal
    if Ntotal is None:
        Nmodes = jnp.max(perm) + 1
        perm = jnp.where(spins > 0, perm, Nmodes)
        arg = jnp.argsort(perm == Nmodes, stable=True)
        perm = perm[arg]
    else:
        indices = jnp.flatnonzero(spins > 0, size=Ntotal)
        perm = perm[indices]

    compare = perm[None, :] > perm[:, None]
    compare = compare[jnp.tril_indices_from(compare, k=-1)]
    sign = jnp.where(jnp.sum(compare) % 2, -1, 1)

    additional_sign = jnp.sum((spins > 0) & (perm_sign < 0))
    perm_sign = jnp.where(additional_sign % 2 == 0, 1, -1).astype(perm_sign.dtype)
    return sign * perm_sign


class FuzzySphereSymmetry (qtx.symmetry.Symmetry):
    
    def __init__(
        self,
        generator: Optional[np.ndarray] = None,
        sector: Union[int, Sequence] = 0,
        generator_sign: Optional[np.ndarray] = None,
        Z2_inversion: int = 0,
        perm: Optional[jax.Array] = None,
        character: Optional[jax.Array] = None,
        perm_sign: Optional[jax.Array] = None,
        ph_sign: Optional[bool] = False,
    ):
            self._ph_sign = ph_sign
            super().__init__(generator, sector, generator_sign, Z2_inversion, perm, character, perm_sign)


    @partial(jax.jit, static_argnums=0)
    def symmetrize(self, psi: qtx.utils.PsiArray, spins: Optional[jax.Array] = None) -> qtx.utils.PsiArray:
        r"""
        Symmetrize the wavefunction as

        .. math::

            \psi^{\mathrm{symm}}(s) = \frac{d}{|G|} \sum_g \mathrm{sign}(s, g) \chi_g \psi(T_g s),
        
        where :math:`d` is the dimension of the group representation,
        :math:`|G|` is the number of elements in the symmetry group, and
        :math:`\mathrm{sign}(s, g)` is the additional sign generated by the symmetry
        depending on the input Fock state (only for fermionic systems).

        :param psi:
            Wavefunctions :math:`\psi(T_i s)`.

        :param spins:
            Input spin or fermion configuration :math:`s`.
            This is only necessary in fermionic systems, where additional
            minus signs :math:`\mathrm{sign}(s, g)` can be generated by the symmetry.

        :return:
            The symmetrized wave function

        .. note::

            This function is jittable.
        """
        if psi.ndim > 1:
            raise ValueError(
                f"Input wavefunction should be 1D, got dimension {psi.ndim}"
            )
        if spins is not None and spins.ndim > 1:
            raise ValueError(f"Input spins should be 1D, got dimension {spins.ndim}")

        if self.is_fermion:
            if spins is None:
                raise RuntimeError(
                    "`symmetrize` can't be performed without input fermion states."
                )
            sign = _permutation_sign(spins, self._perm, self._perm_sign)
            character = sign * self._character
        else:
            character = self._character

        if self.Z2_inversion != 0:
            character = jnp.concatenate([character, self.Z2_inversion * character])
        character = (character * character[0] / character.size).astype(psi.dtype)
        
        if self._ph_sign:
            spins_symm = self.get_symm_spins(spins)
            nperm = spins_symm.shape[0]
            ph_signs_vect = jnp.where( jnp.arange(nperm) < nperm//2, 1, (-1)**(jnp.count_nonzero(spins_symm[jnp.arange(nperm),self.Nsites:] == 1, axis=1)))
            character *= ph_signs_vect
                
        return (psi * character).sum()


    def __matmul__(self, other: FuzzySphereSymmetry) -> FuzzySphereSymmetry:
        r"""
        Generate superposition of two symmetries.

        .. code-block:: python

            from quantax.sites import Square
            from quantax.symmetry import Translation

            lattice = Square(4)
            trans1 = Translation((1, 0))  # translation symmetry in x axis
            trans2 = Translation((0, 1))  # translation symmetry in y axis
            trans2D = trans1 @ trans2  # 2D translation symmetry

        .. warning::
            Users are responsible to ensure the compatibility of different symmetries,
            especially if their generators don't commute.
        """
        generator = np.concatenate([self._generator, other._generator], axis=0)
        sector = [*self._sector, *other._sector]
        g_sign = np.concatenate([self._generator_sign, other._generator_sign], axis=0)
        perm = self._perm[:, other._perm].reshape(-1, self.Nmodes)
        character = jnp.einsum("i,j->ij", self._character, other._character).flatten()
        p_sign = jnp.einsum("is,js->ijs", self._perm_sign, other._perm_sign)
        p_sign = p_sign.reshape(-1, self.Nmodes)
        ph_sign = self._ph_sign | other._ph_sign

        if self.Z2_inversion == 0:
            Z2_inversion = other.Z2_inversion
        elif other.Z2_inversion == 0:
            Z2_inversion = self.Z2_inversion
        elif self.Z2_inversion == other.Z2_inversion:
            Z2_inversion = self.Z2_inversion
        else:
            raise ValueError("Symmetry with different Z2_inversion can't be added")

        new_symm = FuzzySphereSymmetry(
            generator, sector, g_sign, Z2_inversion, perm, character, p_sign, ph_sign
        )
        return new_symm


def IdentityQH() -> FuzzySphereSymmetry:
    """Identity (no symmetry)."""
    global _Identity
    if _Identity is None:
        _Identity = FuzzySphereSymmetry()
    return _Identity


def ParticleHoleQH(eigval: int = 1) -> FuzzySphereSymmetry:
    """
    Particle-hole symmetry for fermion systems.

    :param eigval:
        An integer specifying the symmetry sector. The meaning of each number is

        - 1: Eigenvalue 1 after particle-hole inversion
        - 0: No particle-hole inversion
        - -1: Eigenvalue -1 after particle-hole inversion
    """
    if eigval not in (1, -1):
        raise ValueError("'eigval' of Z2Inversion should be 1 or -1.")
    N = get_sites().Nsites
    generator = np.concatenate([np.arange(N, 2 * N), np.arange(N)])
    global _Z2Inverse
    if eigval not in _Z2Inverse:
        _Z2Inverse[eigval] = FuzzySphereSymmetry(Z2_inversion=eigval, ph_sign=True)
    return _Z2Inverse[eigval]
    

def FlavourPermQH(eigval: int = 1) -> FuzzySphereSymmetry:
    """
    Particle-hole symmetry for fermion systems.

    :param eigval:
        An integer specifying the symmetry sector. The meaning of each number is

        - 1: Eigenvalue 1 after particle-hole inversion
        - 0: No particle-hole inversion
        - -1: Eigenvalue -1 after particle-hole inversion
    """
    if eigval not in (1, -1):
        raise ValueError("'eigval' of Z2Inversion should be 1 or -1.")
    sites = get_sites()
    N = sites.Nsites
    if sites.is_fermion:
        if eigval == 1:
            sector = 0
        elif eigval == -1:
            sector = 1
        else:
            return Identity()
        generator = np.concatenate([np.arange(N, 2 * N), np.arange(N)])
        return FuzzySphereSymmetry(generator, sector)