from typing import Optional

import numpy as np
import jax
import jax.numpy as jnp
import quantax as qtx
from pathlib import Path


def adaptive_learning_rate(lr0, delay, decay, baseline, iteration):
    if iteration < delay:
        return lr0
    else:
        return (lr0 - baseline) * np.exp(-decay*(iteration - delay)) + baseline


def generate_spin_configs(L, N, lz, nsamples):
    configs = np.full((nsamples, 2*L), fill_value = -1)
    for i in range(nsamples):
        for k in range(N):
            spin = np.random.randint(0,2)
            if spin:
                configs[i,k] = 1
            else:
                configs[i,k+N] = 1
        if lz:
            # lz value where more than 1 particle need to hop are not implemented!!
            lz_max = (N//2)*(L - N//2) + (N%2)*((L-1)/2 - N//2)
            if lz > lz_max:
                print("Given Lz exceeds the maximum value.")
                return -1
            else:
                m0 = np.random.randint(0, L-lz)
                configs[i,m0] = -1
                configs[i,m0+N] = -1
                configs[i,m0+lz] = 1
                configs[i,m0+lz+N] = 1
    return configs


def _get_lz_values_from_basis_states(
    basis_states: np.ndarray,
    L: int,
    nflav: int,
) -> np.ndarray:
    basis_states = np.asarray(basis_states)
    spins = qtx.utils.ints_to_array(basis_states, Nmodes=nflav * L)
    occ = (spins > 0).astype(np.int8)
    orbital_idx = np.arange(nflav * L) % L
    doubled_lz = occ @ (2 * orbital_idx - (L - 1))
    return doubled_lz.astype(np.float64) / 2.0


def diagonalize_lz_multiplet(
    multiplet: np.ndarray,
    L: Optional[int] = None,
    nflav: Optional[int] = None,
    symm: Optional[qtx.symmetry.Symmetry] = None,
    basis_states: Optional[np.ndarray] = None,
    *,
    sort: bool = True,
    atol: float = 1e-12,
    return_lz_matrix: bool = False,
):
    """
    Resolve a degenerate Hamiltonian multiplet into states with definite Lz.

    ``multiplet`` should contain the degenerate eigenvectors as columns, as returned
    by ``H.diagonalize``. The vectors must be expressed in the basis generated by
    ``symm``. If ``symm`` is omitted, the current Quantax identity basis is used,
    matching ``H.diagonalize()`` without a symmetry argument.

    This assumes any symmetry used to build the basis preserves Lz, so that Lz is
    diagonal in the symmetry-reduced basis representatives.
    """
    vectors = np.asarray(multiplet)
    was_vector = vectors.ndim == 1
    if was_vector:
        vectors = vectors[:, None]
    if vectors.ndim != 2:
        raise ValueError("`multiplet` must be a vector or a matrix of column vectors.")

    if symm is None and basis_states is None:
        symm = qtx.symmetry.Identity()

    if basis_states is None:
        symm.basis_make()
        basis_states = symm.basis.states
    elif symm is not None:
        symm.basis_make()
    basis_states = np.asarray(basis_states)

    if vectors.shape[0] != basis_states.size:
        raise ValueError(
            "`multiplet` first dimension must match the basis size: "
            f"got {vectors.shape[0]} and {basis_states.size}."
        )

    if L is None:
        sites = qtx.global_defs.get_sites()
        L = sites.Nsites
    if nflav is None:
        sites = qtx.global_defs.get_sites()
        if sites.Nmodes % L != 0:
            raise ValueError("Cannot infer `nflav`; please pass it explicitly.")
        nflav = sites.Nmodes // L

    lz_diag = _get_lz_values_from_basis_states(basis_states, L, nflav)
    ortho_vectors, r = np.linalg.qr(vectors, mode="reduced")
    diag_abs = np.abs(np.diag(r))
    rank_tol = atol * max(vectors.shape)
    if np.any(diag_abs <= rank_tol):
        raise ValueError("`multiplet` contains linearly dependent vectors.")

    lz_matrix = ortho_vectors.conj().T @ (lz_diag[:, None] * ortho_vectors)
    lz_matrix = 0.5 * (lz_matrix + lz_matrix.conj().T)
    lz_values, lz_rotation = np.linalg.eigh(lz_matrix)

    if sort:
        order = np.argsort(lz_values)
        lz_values = lz_values[order]
        lz_rotation = lz_rotation[:, order]

    lz_vectors = ortho_vectors @ lz_rotation
    if np.isrealobj(vectors) and np.allclose(lz_vectors.imag, 0.0, atol=atol):
        lz_vectors = lz_vectors.real

    if was_vector:
        lz_vectors = lz_vectors[:, 0]

    if return_lz_matrix:
        return lz_values, lz_vectors, lz_matrix
    return lz_values, lz_vectors


def _parse_meta_value(raw_value):
    value = raw_value.strip()

    if value == "True":
        return True
    if value == "False":
        return False

    try:
        return int(value)
    except ValueError:
        pass

    try:
        return float(value)
    except ValueError:
        return value


def read_meta_file(run_id, path="."):
    """Read a meta file for a run and return its contents as a dictionary."""
    meta_path = Path(run_id)
    if not meta_path.is_file():
        meta_path = Path(path) / f"meta_{run_id}.txt"

    meta_dict = {}
    with meta_path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            stripped_line = line.strip()
            if not stripped_line:
                continue

            if ":" not in stripped_line:
                raise ValueError(
                    f"Invalid metadata line {line_number} in {meta_path}: {stripped_line}"
                )

            key, value = stripped_line.split(":", 1)
            meta_dict[key.strip()] = _parse_meta_value(value)

    return meta_dict


def add_param_noise(state, sigma=1e-3, seed=None, return_seed=False):
    """
    Add Gaussian noise to the trainable model parameters of a Quantax Variational-like state.

    This does not touch fixed objects such as the operator.
    """
    if seed is None:
        seed = int(np.random.default_rng().integers(0, 2**32, dtype=np.uint32))

    key = jax.random.PRNGKey(seed)

    if jnp.issubdtype(state.dtype, jnp.complexfloating):
        real_dtype = jnp.finfo(state.dtype).dtype
        k1, k2 = jax.random.split(key)

        noise = (
            jax.random.normal(k1, (state.nparams,), dtype=real_dtype)
            + 1j * jax.random.normal(k2, (state.nparams,), dtype=real_dtype)
        )
        noise = (sigma / np.sqrt(2) * noise).astype(state.dtype)
    else:
        noise = sigma * jax.random.normal(
            key,
            (state.nparams,),
            dtype=state.dtype,
        )

    # Quantax update applies theta <- theta - step.
    # To add noise, pass step = -noise.
    state.update(-noise)
    if return_seed:
        return state, seed
    return state
