from __future__ import annotations
from typing import Union, Sequence, Optional, Tuple
import numpy as np
import jax
import jax.numpy as jnp
from functools import partial
import quantax as qtx
from quantax.global_defs import PARTICLE_TYPE, get_sites, get_lattice, get_default_dtype
from quantax.symmetry.symmetry import _permutation_sign
from qhuantax.quantumhall_symmetries import FuzzySphereSymmetry

_Identity = None
_Z2Inverse = dict()


class FuzzySphereActionSymmetry (FuzzySphereSymmetry):
    
    def __init__(
        self,
        base_symm: FuzzySphereSymmetry,
        operator: qtx.operator.Operator
    ):
            self._base_symm = base_symm
            self._operator = operator
            self._operator_dag = operator.H
    
            has_diag = False
            has_off_diag = False
            for opstr, _ in self._operator.op_list:
                nflips = sum(1 for op in opstr if op not in ("I", "n", "z"))
                has_diag |= nflips == 0
                has_off_diag |= nflips > 0
            if has_diag and has_off_diag:
                raise ValueError(
                    "OperatedState currently supports operators that are either entirely "
                    "diagonal or entirely off-diagonal."
                )
            self._mode = "diagonal" if has_diag else "off_diagonal"
    
            super().__init__(base_symm._generator, base_symm._sector, base_symm._generator_sign, base_symm._Z2_inversion,
                             base_symm._perm, base_symm._character, base_symm._perm_sign, base_symm._ph_sign)


    @partial(jax.jit, static_argnums=0)
    def get_symm_spins(self, spins: jax.Array) -> jax.Array:
        r"""
        Get all symmetrized bases :math:`s'=Ts` generated by the symmetry permutations.

        :param spins:
            Input spin or fermion configuration :math:`s`.

        .. note::

            This function is jittable.
        """
        if spins.ndim > 1:
            raise ValueError(f"Input spins should be 1D, got dimension {spins.ndim}")
        
        if self._mode == "diagonal":
            spins = spins[self._perm]
            if self.Z2_inversion != 0:
                spins = jnp.concatenate([spins, -spins], axis=-2)
            return spins

        elif self._mode == "off_diagonal":
            return spins

        


    @partial(jax.jit, static_argnums=0)
    def symmetrize(self, psi: qtx.utils.PsiArray, spins: Optional[jax.Array] = None) -> qtx.utils.PsiArray:
        r"""
        Symmetrize the wavefunction as

        .. math::

            \psi^{\mathrm{symm}}(s) = \frac{d}{|G|} \sum_g \mathrm{sign}(s, g) \chi_g \psi(T_g s),
        
        where :math:`d` is the dimension of the group representation,
        :math:`|G|` is the number of elements in the symmetry group, and
        :math:`\mathrm{sign}(s, g)` is the additional sign generated by the symmetry
        depending on the input Fock state (only for fermionic systems).

        :param psi:
            Wavefunctions :math:`\psi(T_i s)`.

        :param spins:
            Input spin or fermion configuration :math:`s`.
            This is only necessary in fermionic systems, where additional
            minus signs :math:`\mathrm{sign}(s, g)` can be generated by the symmetry.

        :return:
            The symmetrized wave function

        .. note::

            This function is jittable.
        """
        if psi.ndim > 1:
            raise ValueError(
                f"Input wavefunction should be 1D, got dimension {psi.ndim}"
            )
        if spins is not None and spins.ndim > 1:
            raise ValueError(f"Input spins should be 1D, got dimension {spins.ndim}")

        if self.is_fermion:
            if spins is None:
                raise RuntimeError(
                    "`symmetrize` can't be performed without input fermion states."
                )
            sign = _permutation_sign(spins, self._perm, self._perm_sign)
            character = sign * self._character
        else:
            character = self._character

        if self.Z2_inversion != 0:
            character = jnp.concatenate([character, self.Z2_inversion * character])
        character = (character * character[0] / character.size).astype(psi.dtype)
        
        if self._ph_sign:
            spins_symm = self.get_symm_spins(spins)
            nperm = spins_symm.shape[0]
            ph_signs_vect = jnp.where( jnp.arange(nperm) < nperm//2, 1, (-1)**(jnp.count_nonzero(spins_symm[jnp.arange(nperm),self.Nsites:] == 1, axis=1)))
            character *= ph_signs_vect

        spins_symm = self.get_symm_spins(spins)
        spins_symm = spins_symm.reshape(-1, self.Nmodes)
        spins_symm = qtx.utils.to_distribute_array(qtx.utils.array_extend(spins_symm, jax.device_count()))
        action = self._operator.apply_diag(spins_symm)
                
        return (psi * character * action).sum()